{% set name = "geotexxx" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geotexxx-{{ version }}.tar.gz
  sha256: da5d620c1940b77629028f4075bfedbd5ec9a514b2c3c8dfe5718c750caa368e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - pyproj
    - setuptools_scm
    - matplotlib
    - requests

test:
  imports:
    - geotexxx
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Package om geotechnisch grondonderzoek te verwerken
  license: MPL-2.0
  license_file: LICENSE.txt
  home: https://pypi.org/project/geotexxx/

extra:
  recipe-maintainers:
    - ic144
