{% set name = "geotexxx" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geotexxx-{{ version }}.tar.gz
  sha256: 0cba93674f531d51d206b0770a739051e48da9710d692a1fff2528d7a9e99214

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - requests
    - importlib-metadata

test:
  imports:
    - geotexxx
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Package om geotechnisch grondonderzoek te verwerken
  license: MPL-2.0
  license_file: LICENSE.txt
  home: https://pypi.org/project/geotexxx/

extra:
  recipe-maintainers:
    - ic144
