{% set name = "geotexxx" %}
{% set version = "0.1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geotexxx-{{ version }}.tar.gz
  sha256: bd4211beec8e9ad7dd0ad635a0a7ac46849cfadb420a0a36208a918cb73e7246

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - requests
    - importlib-metadata

test:
  imports:
    - geotexxx
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Package om geotechnisch grondonderzoek te verwerken
  license: MPL-2.0
  license_file: LICENSE.txt
  home: https://pypi.org/project/geotexxx/

extra:
  recipe-maintainers:
    - ic144
