{% set name = "geotexxx" %}
{% set version = "0.3.4" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geotexxx-{{ version }}.tar.gz
  sha256: 6fd5aef2d3da69b9f211a53099b5889ffdfefbea98e453fc443b029b0bbef02a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy ==1.26
    - pandas
    - pyproj
    - setuptools_scm
    - matplotlib-base
    - requests

test:
  imports:
    - geotexxx
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Package om geotechnisch grondonderzoek te verwerken
  license: MPL-2.0
  license_file: LICENSE.txt
  home: https://pypi.org/project/geotexxx/

extra:
  recipe-maintainers:
    - ic144
