{% set name = "geotexxx" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geotexxx-{{ version }}.tar.gz
  sha256: 0480c4afd6ad6d16d36dcd75adb16e7656f9c8faa83fdebcca6f7a3dbd10e993

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.11
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >=3.11
    - numpy
    - pandas
    - pyproj
    - matplotlib-base

test:
  imports:
    - geotexxx
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Package om geotechnisch grondonderzoek te verwerken
  license: MPL-2.0
  license_file: LICENSE.txt
  home: https://pypi.org/project/geotexxx/

extra:
  recipe-maintainers:
    - ic144
